# Generated by Django 3.1.3 on 2020-12-27 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20201226_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('can_mark_inappropriate', 'can mark as inappropr'),)},
        ),
    ]
