# Generated by Django 3.1.2 on 2020-11-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201104_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='add_phone_number',
            field=models.CharField(default='', help_text='Extra Phone', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='designation',
            field=models.CharField(default='', help_text='Company Name', max_length=120),
        ),
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=models.CharField(default='', help_text='Company Name', max_length=250),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='', help_text='Your Phone', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='add_phone_number',
            field=models.CharField(default='', help_text='Extra Phone', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(default='', help_text='Company Name', max_length=120),
        ),
        migrations.AlterField(
            model_name='employee',
            name='location',
            field=models.CharField(default='', help_text='Location', max_length=250),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(default='', help_text='Your Phone', max_length=20),
        ),
    ]
